<?php

   namespace dkhru\imageStore\models;

   use Yii;
   use yii\db\Expression;

   /**
    * This is the model class for table "{{%dkh_variant}}".
    *
    * @property integer                                 $id
    * @property integer                                 $width
    * @property integer                                 $height
    * @property string                                  $created_at
    *
    * @property ImageVariant[]                          $imageVariants
    * @property Image[]                                 $images
    *
    * @property \dkhru\imageStore\components\ImageStore $iStore
    */
   class Variant extends \yii\db\ActiveRecord
   {
      public $name;

      /**
       * @inheritdoc
       */
      public static function tableName()
      {
         return '{{%dkh_variant}}';
      }


      /**
       * @inheritdoc
       */
      public function rules()
      {
         return [
            [ [ 'width', 'height' ], 'required' ],
            [ [ 'width', 'height' ], 'integer' ],
            [ [ 'created_at' ], 'safe' ]
         ];
      }

      /**
       * @inheritdoc
       */
      public function attributeLabels()
      {
         return [
            'id'=>Yii::t('dkhImageStore', 'ID'),
            'width'=>Yii::t('dkhImageStore', 'Width'),
            'height'=>Yii::t('dkhImageStore', 'Height'),
            'created_at'=>Yii::t('dkhImageStore', 'Created At'),
         ];
      }

//      public static function find()
//      {
//         return parent::find()->select('*')->addSelect([ 'name'=>new Expression("concat(width,'x',height)") ]); // TODO: Change the autogenerated stub
//      }

      /**
       * @return \yii\db\ActiveQuery
       */
      public function getImageVariants()
      {
         return $this->hasMany(ImageVariant::className(), [ 'variant_id'=>'id' ]);
      }

      /**
       * @return \yii\db\ActiveQuery
       */
      public function getImages()
      {
         return $this->hasMany(Image::className(), [ 'id'=>'image_id' ])->viaTable('{{%dkh_image_variant}}', [ 'variant_id'=>'id' ]);
      }
      
   }
